#pragma once
#undef MATRIX_ROWS
#undef MATRIX_COLS
#define MATRIX_ROWS 4
#define MATRIX_COLS 32
#define DIODE_DIRECTION COL2ROW

#define CONFIG_PIN_SDA 18
#define CONFIG_PIN_SCL 16

#define PIMORONI_TRACKBALL_INTERVAL_MS 8
